### ISSUE TITLE
about forward

### ISSUE THREAD

**Issue by chencodeX** [automan000/Convolution_LSTM_PyTorch#5]
I'm very happy to see that you have modified the previous question, but I suggest that your ConvLSTMCell  forward process take the following calculations:
        ci = torch.sigmoid(self.Wxi(input) + self.Whi(hidden_state) + c * self.Wci)
        cf = torch.sigmoid(self.Wxf(input) + self.Whf(hidden_state) + c * self.Wcf)
        new_c = cf * c + ci * torch.tanh(self.Wxc(input) + self.Whc(hidden_state))
        co = torch.sigmoid(self.Wxo(input) + self.Who(hidden_state) + new_c * self.Wco)
        new_h = co * torch.tanh(new_c)

**Comment by automan000** [comment]
Sorry for the silly mistake.
