### ISSUE TITLE
RuntimeError: Jacobian mismatch for output 0 with respect to input 0

### ISSUE THREAD

**Issue by inkplay** [automan000/Convolution_LSTM_PyTorch#6]
Default code snippet ran in pytorch 0.40, it hangs a bit then this error shows up.

Complete Error:

`RuntimeError                              Traceback (most recent call last)
<ipython-input-8-c004ad9bde11> in <module>()
    101     output = convlstm(input)
    102     output = output[0][0]
--> 103     res = torch.autograd.gradcheck(loss_fn, (output, target), raise_exception=True)
    104     print(res)

C:\Anaconda3\lib\site-packages\torch\autograd\gradcheck.py in gradcheck(func, inputs, eps, atol, rtol, raise_exception)
    190                 if not ((a - n).abs() <= (atol + rtol * n.abs())).all():
    191                     return fail_test('Jacobian mismatch for output %d with respect to input %d,\n'
--> 192                                      'numerical:%s\nanalytical:%s\n' % (i, j, n, a))
    193 
    194         if not reentrant:

C:\Anaconda3\lib\site-packages\torch\autograd\gradcheck.py in fail_test(msg)
    170     def fail_test(msg):
    171         if raise_exception:
--> 172             raise RuntimeError(msg)
    173         return False
    174 

RuntimeError: Jacobian mismatch for output 0 with respect to input 0,
numerical:tensor(1.00000e-02 *
       [[ 0.0000],
        [ 0.0000],
        [ 0.0000],
        ...,
        [ 0.0000],
        [ 0.0000],
        [ 0.0000]])
analytical:tensor([[-3.6467e-05],
        [ 2.2621e-06],
        [-3.9878e-05],
        ...,
        [-4.3014e-05],
        [ 1.2278e-05],
        [ 3.6285e-06]])`

**Comment by umbra007** [comment]
I had the same error. Gradcheck requires double precision numbers to run. By changing all the tensors and modules to double precision the code will run fine and return True. You can change them with .double().
A more detailed explanation can be found here:
https://discuss.pytorch.org/t/why-is-nn-linear-failing-gradcheck-is-there-a-bug-in-gradcheck/17346

**Comment by automan000** [comment]
Thank you all. I will update the code soon.

**Comment by CJEQ** [comment]
You just need to change the `res = torch.autograd.gradcheck(loss_fn, (output, target), raise_exception=True)` to `res = torch.autograd.gradcheck(loss_fn, (output, target), eps=1e-2, atol=1e-2, raise_exception=True)`
