### ISSUE TITLE
关于input 和 step 的问题

### ISSUE THREAD

**Issue by Fzz123** [automan000/Convolution_LSTM_PyTorch#7]
代码的输入数据定义为: input = Variable(torch.randn(1, 512, 64, 32)).cuda()  参数分别为(batch_size, channels, height, weight) 
在输入convlstm网络进行计算时有下面这个for循环：
`for step in range(self.step):
    x= input
    for i in range(self.num_layers):
    ...
`
 

请问这个循环每次的输入x都是相同的吗？序列体现在哪里呢？有理解不对的地方希望能得到您的指正，谢谢！

**Comment by automan000** [comment]
Please have a look at my email:)

**Comment by XiaoAHeng** [comment]
> 你只需要在不同step输入不同的x即可~
如果用这个代码，同一num_layer的的不同step之间好像没有信息的传递啊
