### ISSUE TITLE
Why Wci,Wcf,Wco should be initialized at the beginning of  each batch? 

### ISSUE THREAD

**Issue by SampsonKwan** [automan000/Convolution_LSTM_PyTorch#9]
@automan000  Thanks a lot for you work! I am a little confused that in code: 

>
> 41     def init_hidden(self, batch_size, hidden, shape):
>  42     ¦   self.Wci = Variable(torch.zeros(1, hidden, shape[0], shape[1])).cuda()
>  43     ¦   self.Wcf = Variable(torch.zeros(1, hidden, shape[0], shape[1])).cuda()
>  44     ¦   self.Wco = Variable(torch.zeros(1, hidden, shape[0], shape[1])).cuda()
>  45     ¦   return (Variable(torch.zeros(batch_size, hidden, shape[0], shape[1])).cuda(),
>  46     ¦   ¦   ¦   Variable(torch.zeros(batch_size, hidden, shape[0], shape[1])).cuda())

Why Wci, Wcf, Wco should be initialized?

**Comment by ppalasek** [comment]
Hi,

I agree with @SampsonKwan that initialising `Wci`, `Wcf` and `Wco` to zero at the beginning of each batch doesn't make sense as this way `C_{t-1}` won't be used when calculating `i_t`, `f_t` and `o_t` in Equation 3 from the paper (as we'd just multiply it with zeros).

I'd say that this is a bug, and that `Wci`, `Wcf` and `Wco` should be initialised in the `__init__` of `ConvLSTMCell`.

**Comment by Hzzone** [comment]
Yes, I agree with all above. According to formula in the paper, if Wci, Wcf and Whc is all initialized as zero in every batch, cell output will not be used or make sense in anymore. The implementation of this repor can not work because I have tried to train my own data. At the same time, the weights should be initialized every time is cell output and hidden state, if they are initially None.

**Comment by automan000** [comment]
@Hzzone @ppalasek @SampsonKwan Thanks you guys. I will upload a new version. In the current implementation, I try to share the states accorss the cells. That's a mistake.

**Comment by Hzzone** [comment]
@automan000 
Thanks for your work, here is my simple implementation for ConvLSTM:
```python
from torch import nn
import torch

class ConvLSTM(nn.Module):
    def __init__(self, input_channel, hidden_size, b_h_w, kernel_size, stride=1, padding=1):
        super().__init__()
        self._conv = nn.Conv2d(in_channels=input_channel + hidden_size,
                               out_channels=hidden_size*4,
                               kernel_size=kernel_size,
                               stride=stride,
                               padding=padding)
        self._state_height, self._state_width = b_h_w
        self.Wci = torch.zeros(1, hidden_size, self._state_height, self._state_width)
        self.Wcf = torch.zeros(1, hidden_size, self._state_height, self._state_width)
        self.Wco = torch.zeros(1, hidden_size, self._state_height, self._state_width)
        self.Wci.requires_grd = True
        self.Wcf.requires_grd = True
        self.Wco.requires_grd = True
        self._input_channel = input_channel
        self._hidden_size = hidden_size

    # inputs and states should not be all none
    # inputs: S*B*C*H*W
    def forward(self, inputs=None, states=None, seq_len=cfg.HKO.BENCHMARK.IN_LEN):

        # initial inputs
        if inputs is None:
            inputs = torch.zeros((inputs.size(1), self._input_channel, self._state_height,
                                  self._state_width), dtype=torch.float).to(cfg.GLOBAL.DEVICE)
        if states is None:
            c = torch.zeros((inputs.size(1), self._hidden_size, self._state_height,
                                  self._state_width), dtype=torch.float).to(cfg.GLOBAL.DEVICE)
            h = torch.zeros((inputs.size(1), self._hidden_size, self._state_height,
                             self._state_width), dtype=torch.float).to(cfg.GLOBAL.DEVICE)
        else:
            h, c = states

        outputs = []
        for i in range(seq_len):
            cat_x = torch.cat([inputs, h], dim=1)
            conv_x = self._conv(cat_x)

            i, f, tmp_c, o = torch.chunk(conv_x, 4, dim=1)

            i = torch.sigmoid(i+self.Wci*c)
            f = torch.sigmoid(f+self.Wcf*c)
            c = f*c + i*torch.tanh(tmp_c)
            o = torch.sigmoid(o+self.Wco*c)
            h = o*torch.tanh(c)
            outputs.append(h)
        return torch.stack(outputs), (h, c)
```

**Comment by automan000** [comment]
Issue solved

**Comment by bkoyuncu** [comment]
Is the explicitly said to initialize with zero or just a choice? I could not find in the paper
